version: "3.9"

services:
  app:
    # Build configuration
    build:
      context: .
      dockerfile: Dockerfile

    # Optional container name
    container_name: gpp-2fa-app

    # Port mapping
    ports:
      - "5000:8080"

    # Volume mounts
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

    # Environment variables
    environment:
      - TZ=UTC

    # Restart policy
    restart: unless-stopped


volumes:
  seed-data:
  cron-output:
